"""empty message

Revision ID: e98e81fed747
Revises: df553bf0a045
Create Date: 2024-10-28 15:59:34.867536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98e81fed747'
down_revision = 'df553bf0a045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_c', schema=None) as batch_op:
        batch_op.drop_index('ix_business_c_index')

    op.drop_table('business_c')
    op.drop_table('b2')
    op.drop_table('inv_ch6')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inv_ch6',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('recipients', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('b2',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('legal_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('legal_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('founding_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ar_reminder_flag', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_ar_reminder_year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('op_state', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('corp_class', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nano_id', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('business_c',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('legal_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('legal_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nano_id', sa.TEXT(), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('business_c', schema=None) as batch_op:
        batch_op.create_index('ix_business_c_index', ['index'], unique=False)

    # ### end Alembic commands ###
