name: Business AR Process Paid Fillings CI

on:
  pull_request:
    paths:
      - "jobs/process_paid_filings/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./jobs/process_paid_filings

jobs:
  business-ar-job-process-paid-filings-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "business-ar-job-process-paid-filings"
      working_directory: "./jobs/process_paid_filings"
      codecov_flag: "businessarprocess_paid_filings"
      skip_isort: "true"
      skip_black: "true"