name: Business AR API CI

on:
  pull_request:
    paths:
      - "api/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./api

jobs:
  business-ar-api-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "business-ar-api"
      working_directory: "./api"
      codecov_flag: "businessarapi"
      skip_isort: "true"
      skip_black: "true"