name: Business AR Admin UI CD

on:
  push:
    branches:
      - main
    paths:
      - "web/admin/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
        - dev
        - test
        - sandbox
        - prod

jobs:
  business-ar-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "business-ar-ui"
      working_directory: "./web/admin"
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
